#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
source \
  "${_lib}/libcrash-bash/crash-bash"

_global_variables() {
  override_quiet="y"
  out_file=""
  _host=""
  _user=""
  _port=""
  tor_transport=""
  quiet="y"
}

# Writes SSH configuration
_ssh_conf() {
  local \
    _out="${1}" \
    _host="${2}" \
    _hostname="${3}" \
    _user="${4}" \
    _port="${5}" \
    _tor="${6}" \
    _out \
    _cfg=()
  _cfg=(
    "Host ${_host}"
    "  HostName ${_hostname}"
    "  Port ${_port}"
    "  IdentityFile ${HOME}/.ssh/${_host}"
    "  User ${_user}"
  )
  if \
    [[ "${_hostname}" == *".onion" ]] || \
    [[ "${_tor}" == "true" ]]; then
    _cfg=(
      "Host ${_host}"
      "  HostName ${_hostname}"
      "  Port ${_port}"
      "  IdentityFile ${HOME}/.ssh/${_host}"
      "  User ${_user}"
    )
  fi
  printf \
    '%s\n' \
    "${_cfg[@]}" > \
    "${_out}"
  chmod \
    600 \
    "${_out}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
    IFS='' read -r -d '' usagetext <<ENDUSAGETEXT || true
usage:
  ${app_name}
    [options] 
      <out>
      <host>
      <hostname>
      <user>
      <port>
  options:
     -t               Explicitly enable tor transport
     -h               This message
     -v               Enable verbose output

  out:                Path of the resulting configuration file
  host:               Name of the resulting host
  hostname:           Address
  user:               User to connect to
  port:               Port to connect to
ENDUSAGETEXT
    printf \
      '%s' \
      "${usagetext}"
    exit "${1}"
}

_globals
_global_variables

while getopts 'tvh?' arg; do
  case "${arg}" in
    t) override_tor_transport="y" ;;
    v) override_quiet="n" ;;
    h|?) _usage 0 ;;
    *)
        _msg_error \
          "Invalid argument '${arg}'" 0
        _usage 0
        ;;
  esac
done

shift \
  $((OPTIND - 1))
if (( $# < 5 )); then
  _msg_error \
    "Missing argument." \
    0
  _usage 0
fi

out_file="${1}"
target_host="${2}"
target_hostname="${3}"
target_user="${4}"
target_port="${5}"
shift \
  5
_args=(
  "$@"
)

_ssh_conf \
  "${out_file}" \
  "${target_host}" \
  "${target_hostname}" \
  "${target_user}" \
  "${target_port}" \
  "${_args[@]}"

# vim:set sw=2 sts=-1 et:
